customers:
  - name: EACC
    environments:
      - name: Development
        version: "23.1.1.3"
        attributes:
          qdrive: "//nz22dev1/supported_systems"
          appservice: "https://nz22devapp1.sdsi.local/CAD.AppService/#"
          install_path: "C:\\WorkstationLaunches\\EACC_Dev_23.exe"
      - name: Support
        version: "23.1.1.3"
        attributes:
          qdrive: "//nz23sup1/supported_systems"
          appservice: "https://nz23supapp1.sdsi.local/CAD.AppService/#"
          install_path: "C:\\WorkstationLaunches\\EACC_Sup_23.exe"
  - name: QAS
    environments:
      - name: Project
        version: "23.1.3.3"
        attributes:
          qdrive: "//qas23dev1/EnterpriseCAD"
          appservice: "https://qas23devapp1.sdsi.local/CAD.AppService/#"
          install_path: "C:\\WorkstationLaunches\\QAS_Dev_23.exe"
      - name: Support
        version: "5.8"
        attributes:
          qdrive: "//supqas/Supported_Systems"
  - name: NSW
    environments:
      - name: Project
        version: "23.1.3.3"
        attributes:
          qdrive: "//nsw23dev1/supported_systems"
          appservice: "https://nsw23devapp1.sdsi.local/CAD.AppService/#"
          install_path: "C:\\WorkstationLaunches\\NSW_Dev_23.exe"
      - name: Support
        version: "5.8"
        attributes:
          qdrive: "//nswsup/supported_systems"